######
### BLC_ADDRESS
######
ALTER TABLE BLC_ADDRESS ADD COLUMN `EMAIL_ADDRESS` varchar(255) DEFAULT NULL;
ALTER TABLE BLC_ADDRESS ADD COLUMN `FAX` varchar(255) DEFAULT NULL;

######
### BLC_CATEGORY
######
ALTER TABLE BLC_CATEGORY ADD COLUMN `ARCHIVED` char(1) DEFAULT NULL;

######
### BLC_CUSTOMER
######
ALTER TABLE BLC_CUSTOMER ADD COLUMN `DEACTIVATED` bit(1) DEFAULT NULL;

######
### BLC_CUSTOMER_ADDRESS
######
ALTER TABLE BLC_CUSTOMER_ADDRESS ADD COLUMN `DEFAULT_FLAG` bit(1) DEFAULT NULL;

######
### BLC_FULFILLMENT_GROUP
######
# Add columns
ALTER TABLE BLC_FULFILLMENT_GROUP ADD COLUMN `FULFILLMENT_OPTION_ID` bigint(20) DEFAULT NULL;
ALTER TABLE BLC_FULFILLMENT_GROUP ADD KEY `FKC5B9EF1881F34C7F` (`FULFILLMENT_OPTION_ID`);
ALTER TABLE BLC_FULFILLMENT_GROUP ADD CONSTRAINT `FKC5B9EF1881F34C7F` FOREIGN KEY (`FULFILLMENT_OPTION_ID`) REFERENCES `BLC_FULFILLMENT_OPTION` (`FULFILLMENT_OPTION_ID`);

######
### BLC_FULFILLMENT_GROUP_FEE
######
# Added columns
ALTER TABLE BLC_FULFILLMENT_GROUP_FEE ADD COLUMN `TOTAL_FEE_TAX` decimal(19,5) DEFAULT NULL;
# Modified columns
ALTER TABLE BLC_FULFILLMENT_GROUP_FEE CHANGE `IS_TAXABLE` `FEE_TAXABLE_FLAG` bit(1) DEFAULT NULL;

######
### BLC_FULFILLMENT_GROUP_ITEM
######
# Drop the unique index to change from @OneToOne to @ManyToOne
ALTER TABLE BLC_FULFILLMENT_GROUP_ITEM DROP INDEX `ORDER_ITEM_ID`;

######
### BLC_ORDER
######
ALTER TABLE BLC_ORDER DROP COLUMN `CITY_TAX`;
ALTER TABLE BLC_ORDER DROP COLUMN `COUNTRY_TAX`;
ALTER TABLE BLC_ORDER DROP COLUMN `COUNTY_TAX`;
ALTER TABLE BLC_ORDER DROP COLUMN `DISTRICT_TAX`;
ALTER TABLE BLC_ORDER DROP COLUMN `STATE_TAX`;

######
### BLC_ORDER_ITEM
######
ALTER TABLE BLC_ORDER_ITEM ADD COLUMN `ITEM_TAXABLE_FLAG` bit(1) DEFAULT NULL;
ALTER TABLE BLC_ORDER_ITEM ADD COLUMN `SPLIT_PARENT_ITEM_ID` bigint(20) DEFAULT NULL;

######
### BLC_PAGE
######
ALTER TABLE BLC_PAGE ADD COLUMN `OFFLINE_FLAG` bit(1) DEFAULT NULL;
ALTER TABLE BLC_PAGE ADD COLUMN `PRIORITY` int(11) DEFAULT NULL;

######
### BLC_PRODUCT_CROSS_SALE
######
# Added columns
ALTER TABLE BLC_PRODUCT_CROSS_SALE ADD COLUMN `CATEGORY_ID` bigint(20) DEFAULT NULL;
ALTER TABLE BLC_PRODUCT_CROSS_SALE ADD KEY `CROSSSALE_CATEGORY_INDEX` (`CATEGORY_ID`);
ALTER TABLE BLC_PRODUCT_CROSS_SALE ADD KEY `FK8324FB3C15D1A13D` (`CATEGORY_ID`);
ALTER TABLE BLC_PRODUCT_CROSS_SALE ADD CONSTRAINT `FK8324FB3C15D1A13D` FOREIGN KEY (`CATEGORY_ID`) REFERENCES `BLC_CATEGORY` (`CATEGORY_ID`);
# Modified columns
ALTER TABLE BLC_PRODUCT_CROSS_SALE CHANGE `PRODUCT_ID` `PRODUCT_ID` bigint(20) DEFAULT NULL;

######
### BLC_PRODUCT_SKU_XREF
######
ALTER TABLE BLC_PRODUCT_SKU_XREF CHANGE `PRODUCT_ID` `PRODUCT_ID` bigint(20) DEFAULT NULL;
ALTER TABLE BLC_PRODUCT_SKU_XREF ADD PRIMARY KEY (`SKU_ID`)

######
### BLC_PRODUCT_UP_SALE
######
ALTER TABLE BLC_PRODUCT_UP_SALE ADD COLUMN `CATEGORY_ID` bigint(20) DEFAULT NULL;
ALTER TABLE BLC_PRODUCT_UP_SALE ADD KEY `UPSALE_CATEGORY_INDEX` (`CATEGORY_ID`);
ALTER TABLE BLC_PRODUCT_UP_SALE ADD KEY `FKF69054F515D1A13D` (`CATEGORY_ID`);
ALTER TABLE BLC_PRODUCT_UP_SALE ADD CONSTRAINT `FKF69054F515D1A13D` FOREIGN KEY (`CATEGORY_ID`) REFERENCES `BLC_CATEGORY` (`CATEGORY_ID`);

######
### BLC_SANDBOX_ITEM
######
# Added Columns
ALTER TABLE BLC_SANDBOX_ITEM ADD COLUMN `GRP_DESCRIPTION` varchar(255) DEFAULT NULL;
ALTER TABLE BLC_SANDBOX_ITEM ADD COLUMN `ROOT_ENTITY_ITEM` bit(1) DEFAULT NULL;
ALTER TABLE BLC_SANDBOX_ITEM ADD KEY `ROOT_ENTY_ITM_INDEX` (`ROOT_ENTITY_ITEM`);
# Removed Columns
# If this query fails because of a wrong name, drop the constraint that matches this definition:
# FOREIGN KEY (`ORIG_SANDBOX_ID`) REFERENCES `BLC_SANDBOX` (`SANDBOX_ID`)
ALTER TABLE BLC_SANDBOX_ITEM  DROP KEY `ORIG_SANDBOX_ID`;
ALTER TABLE BLC_SANDBOX_ITEM  DROP KEY `FK48435EF153908C53`;

# If this query fails because of a wrong name, drop the constraint that matches this definition:
# FOREIGN KEY (`SANDBOX_ID`) REFERENCES `BLC_SANDBOX` (`SANDBOX_ID`)
ALTER TABLE BLC_SANDBOX_ITEM  DROP KEY `SANDBOX_ID`;
ALTER TABLE BLC_SANDBOX_ITEM DROP KEY `FK48435EF19B942795`;

######
### BLC_ADMIN_ROLE
######
ALTER TABLE BLC_ADMIN_ROLE DROP KEY `NAME`;
ALTER TABLE BLC_ADMIN_ROLE ADD UNIQUE KEY `NAME` (`NAME`);

######
### BLC_CREDIT_CARD_PAYMENT
######
ALTER TABLE BLC_CREDIT_CARD_PAYMENT ADD COLUMN `NAME_ON_CARD` varchar(255) NOT NULL;

######
### BLC_OFFER
######
# Added columns
ALTER TABLE BLC_OFFER ADD COLUMN `ARCHIVED` char(1) DEFAULT NULL;
ALTER TABLE BLC_OFFER ADD COLUMN `QUALIFYING_ITEM_MIN_TOTAL` decimal(19,5) DEFAULT NULL;
# Modified columns
ALTER TABLE BLC_OFFER CHANGE `APPLIES_WHEN_RULES` `APPLIES_WHEN_RULES` longtext;
ALTER TABLE BLC_OFFER CHANGE `APPLIES_TO_RULES` `APPLIES_TO_RULES` longtext;

######
### BLC_STORE
######
# Modified columns
ALTER TABLE BLC_STORE CHANGE `LATITUDE` `LATITUDE` double DEFAULT NULL;
ALTER TABLE BLC_STORE CHANGE `LONGITUDE` `LONGITUDE` double DEFAULT NULL;

######
### SEQUENCE_GENERATOR
######
ALTER TABLE SEQUENCE_GENERATOR CHANGE `ID_NAME` `ID_NAME` varchar(255) NOT NULL;
ALTER TABLE SEQUENCE_GENERATOR CHANGE `ID_VAL` `ID_VAL` bigint(20) DEFAULT NULL;
ALTER TABLE SEQUENCE_GENERATOR ADD PRIMARY KEY (`ID_NAME`);
