    /*!40101 SET @saved_cs_client     = @@character_set_client */;
    /*!40101 SET character_set_client = utf8 */;
    CREATE TABLE `BLC_CAT_SEARCH_FACET_EXCL_XREF` (
      `CATEGORY_ID` bigint(20) NOT NULL,
      `SEARCH_FACET_ID` bigint(20) NOT NULL,
      KEY `FK8361EF4EB96B1C93` (`SEARCH_FACET_ID`),
      KEY `FK8361EF4E15D1A13D` (`CATEGORY_ID`),
      CONSTRAINT `FK8361EF4E15D1A13D` FOREIGN KEY (`CATEGORY_ID`) REFERENCES `BLC_CATEGORY` (`CATEGORY_ID`),
      CONSTRAINT `FK8361EF4EB96B1C93` FOREIGN KEY (`SEARCH_FACET_ID`) REFERENCES `BLC_SEARCH_FACET` (`SEARCH_FACET_ID`)
    ) ENGINE=InnoDB DEFAULT CHARSET=latin1;
    /*!40101 SET character_set_client = @saved_cs_client */;

    LOCK TABLES `BLC_CAT_SEARCH_FACET_EXCL_XREF` WRITE;
    /*!40000 ALTER TABLE `BLC_CAT_SEARCH_FACET_EXCL_XREF` DISABLE KEYS */;
    /*!40000 ALTER TABLE `BLC_CAT_SEARCH_FACET_EXCL_XREF` ENABLE KEYS */;
    UNLOCK TABLES;

    /*!40101 SET @saved_cs_client     = @@character_set_client */;
    /*!40101 SET character_set_client = utf8 */;
    CREATE TABLE `BLC_CAT_SEARCH_FACET_XREF` (
      `CATEGORY_SEARCH_FACET_ID` bigint(20) NOT NULL,
      `POSITION` int(11) DEFAULT NULL,
      `CATEGORY_ID` bigint(20) DEFAULT NULL,
      `SEARCH_FACET_ID` bigint(20) DEFAULT NULL,
      PRIMARY KEY (`CATEGORY_SEARCH_FACET_ID`),
      KEY `FK32210EEBB96B1C93` (`SEARCH_FACET_ID`),
      KEY `FK32210EEB15D1A13D` (`CATEGORY_ID`),
      CONSTRAINT `FK32210EEB15D1A13D` FOREIGN KEY (`CATEGORY_ID`) REFERENCES `BLC_CATEGORY` (`CATEGORY_ID`),
      CONSTRAINT `FK32210EEBB96B1C93` FOREIGN KEY (`SEARCH_FACET_ID`) REFERENCES `BLC_SEARCH_FACET` (`SEARCH_FACET_ID`)
    ) ENGINE=InnoDB DEFAULT CHARSET=latin1;
    /*!40101 SET character_set_client = @saved_cs_client */;

    LOCK TABLES `BLC_CAT_SEARCH_FACET_XREF` WRITE;
    /*!40000 ALTER TABLE `BLC_CAT_SEARCH_FACET_XREF` DISABLE KEYS */;
    /*!40000 ALTER TABLE `BLC_CAT_SEARCH_FACET_XREF` ENABLE KEYS */;
    UNLOCK TABLES;
    
    DROP TABLE IF EXISTS `BLC_CUSTOMER_ATTRIBUTE`;
    /*!40101 SET @saved_cs_client     = @@character_set_client */;
    /*!40101 SET character_set_client = utf8 */;
    CREATE TABLE `BLC_CUSTOMER_ATTRIBUTE` (
      `CUSTOMER_ATTR_ID` bigint(20) NOT NULL,
      `NAME` varchar(255) NOT NULL,
      `VALUE` varchar(255) NOT NULL,
      `CUSTOMER_ID` bigint(20) NOT NULL,
      PRIMARY KEY (`CUSTOMER_ATTR_ID`),
      KEY `FKB974C8217470F437` (`CUSTOMER_ID`),
      CONSTRAINT `FKB974C8217470F437` FOREIGN KEY (`CUSTOMER_ID`) REFERENCES `BLC_CUSTOMER` (`CUSTOMER_ID`)
    ) ENGINE=InnoDB DEFAULT CHARSET=latin1;
    /*!40101 SET character_set_client = @saved_cs_client */;

    --
    -- Dumping data for table `BLC_CUSTOMER_ATTRIBUTE`
    --

    LOCK TABLES `BLC_CUSTOMER_ATTRIBUTE` WRITE;
    /*!40000 ALTER TABLE `BLC_CUSTOMER_ATTRIBUTE` DISABLE KEYS */;
    /*!40000 ALTER TABLE `BLC_CUSTOMER_ATTRIBUTE` ENABLE KEYS */;
    UNLOCK TABLES;

    DROP TABLE IF EXISTS `BLC_CUSTOMER_PASSWORD_TOKEN`;
    /*!40101 SET @saved_cs_client     = @@character_set_client */;
    /*!40101 SET character_set_client = utf8 */;
    CREATE TABLE `BLC_CUSTOMER_PASSWORD_TOKEN` (
      `PASSWORD_TOKEN` varchar(255) NOT NULL,
      `CREATE_DATE` datetime NOT NULL,
      `CUSTOMER_ID` bigint(20) NOT NULL,
      `TOKEN_USED_DATE` datetime DEFAULT NULL,
      `TOKEN_USED_FLAG` bit(1) NOT NULL,
      PRIMARY KEY (`PASSWORD_TOKEN`)
    ) ENGINE=InnoDB DEFAULT CHARSET=latin1;
    /*!40101 SET character_set_client = @saved_cs_client */;

    --
    -- Dumping data for table `BLC_CUSTOMER_PASSWORD_TOKEN`
    --

    LOCK TABLES `BLC_CUSTOMER_PASSWORD_TOKEN` WRITE;
    /*!40000 ALTER TABLE `BLC_CUSTOMER_PASSWORD_TOKEN` DISABLE KEYS */;
    /*!40000 ALTER TABLE `BLC_CUSTOMER_PASSWORD_TOKEN` ENABLE KEYS */;
    UNLOCK TABLES;
    
    DROP TABLE IF EXISTS `BLC_DATA_DRIVEN_ENUMERATION`;
    /*!40101 SET @saved_cs_client     = @@character_set_client */;
    /*!40101 SET character_set_client = utf8 */;
    CREATE TABLE `BLC_DATA_DRIVEN_ENUMERATION` (
      `ENUMERATION_ID` bigint(20) NOT NULL,
      `DISPLAY` varchar(255) DEFAULT NULL,
      `HIDDEN` bit(1) DEFAULT NULL,
      `ENUM_KEY` varchar(255) DEFAULT NULL,
      `MODIFIABLE` bit(1) DEFAULT NULL,
      `ENUM_TYPE` bigint(20) DEFAULT NULL,
      PRIMARY KEY (`ENUMERATION_ID`),
      KEY `HIDDEN_INDEX` (`HIDDEN`),
      KEY `KEY_INDEX` (`ENUM_KEY`),
      KEY `FK648BF83BA60E0554` (`ENUM_TYPE`),
      CONSTRAINT `FK648BF83BA60E0554` FOREIGN KEY (`ENUM_TYPE`) REFERENCES `BLC_DATA_DRIVEN_ENUMERATION` (`ENUMERATION_ID`)
    ) ENGINE=InnoDB DEFAULT CHARSET=latin1;
    /*!40101 SET character_set_client = @saved_cs_client */;

    --
    -- Dumping data for table `BLC_DATA_DRIVEN_ENUMERATION`
    --

    LOCK TABLES `BLC_DATA_DRIVEN_ENUMERATION` WRITE;
    /*!40000 ALTER TABLE `BLC_DATA_DRIVEN_ENUMERATION` DISABLE KEYS */;
    /*!40000 ALTER TABLE `BLC_DATA_DRIVEN_ENUMERATION` ENABLE KEYS */;
    UNLOCK TABLES;
    
    DROP TABLE IF EXISTS `BLC_FG_FEE_TAX_XREF`;
    /*!40101 SET @saved_cs_client     = @@character_set_client */;
    /*!40101 SET character_set_client = utf8 */;
    CREATE TABLE `BLC_FG_FEE_TAX_XREF` (
      `FULFILLMENT_GROUP_FEE_ID` bigint(20) NOT NULL,
      `TAX_DETAIL_ID` bigint(20) NOT NULL,
      UNIQUE KEY `TAX_DETAIL_ID` (`TAX_DETAIL_ID`),
      KEY `FK25426DC0598F6D02` (`FULFILLMENT_GROUP_FEE_ID`),
      KEY `FK25426DC071448C19` (`TAX_DETAIL_ID`),
      CONSTRAINT `FK25426DC071448C19` FOREIGN KEY (`TAX_DETAIL_ID`) REFERENCES `BLC_TAX_DETAIL` (`TAX_DETAIL_ID`),
      CONSTRAINT `FK25426DC0598F6D02` FOREIGN KEY (`FULFILLMENT_GROUP_FEE_ID`) REFERENCES `BLC_FULFILLMENT_GROUP_FEE` (`FULFILLMENT_GROUP_FEE_ID`)
    ) ENGINE=InnoDB DEFAULT CHARSET=latin1;
    /*!40101 SET character_set_client = @saved_cs_client */;

    --
    -- Dumping data for table `BLC_FG_FEE_TAX_XREF`
    --

    LOCK TABLES `BLC_FG_FEE_TAX_XREF` WRITE;
    /*!40000 ALTER TABLE `BLC_FG_FEE_TAX_XREF` DISABLE KEYS */;
    /*!40000 ALTER TABLE `BLC_FG_FEE_TAX_XREF` ENABLE KEYS */;
    UNLOCK TABLES;

    --
    -- Table structure for table `BLC_FG_FG_TAX_XREF`
    --

    DROP TABLE IF EXISTS `BLC_FG_FG_TAX_XREF`;
    /*!40101 SET @saved_cs_client     = @@character_set_client */;
    /*!40101 SET character_set_client = utf8 */;
    CREATE TABLE `BLC_FG_FG_TAX_XREF` (
      `FULFILLMENT_GROUP_ID` bigint(20) NOT NULL,
      `TAX_DETAIL_ID` bigint(20) NOT NULL,
      UNIQUE KEY `TAX_DETAIL_ID` (`TAX_DETAIL_ID`),
      KEY `FK61BEA45571448C19` (`TAX_DETAIL_ID`),
      KEY `FK61BEA4555028DC55` (`FULFILLMENT_GROUP_ID`),
      CONSTRAINT `FK61BEA4555028DC55` FOREIGN KEY (`FULFILLMENT_GROUP_ID`) REFERENCES `BLC_FULFILLMENT_GROUP` (`FULFILLMENT_GROUP_ID`),
      CONSTRAINT `FK61BEA45571448C19` FOREIGN KEY (`TAX_DETAIL_ID`) REFERENCES `BLC_TAX_DETAIL` (`TAX_DETAIL_ID`)
    ) ENGINE=InnoDB DEFAULT CHARSET=latin1;
    /*!40101 SET character_set_client = @saved_cs_client */;

    --
    -- Dumping data for table `BLC_FG_FG_TAX_XREF`
    --

    LOCK TABLES `BLC_FG_FG_TAX_XREF` WRITE;
    /*!40000 ALTER TABLE `BLC_FG_FG_TAX_XREF` DISABLE KEYS */;
    /*!40000 ALTER TABLE `BLC_FG_FG_TAX_XREF` ENABLE KEYS */;
    UNLOCK TABLES;

    --
    -- Table structure for table `BLC_FG_ITEM_TAX_XREF`
    --

    DROP TABLE IF EXISTS `BLC_FG_ITEM_TAX_XREF`;
    /*!40101 SET @saved_cs_client     = @@character_set_client */;
    /*!40101 SET character_set_client = utf8 */;
    CREATE TABLE `BLC_FG_ITEM_TAX_XREF` (
      `FULFILLMENT_GROUP_ITEM_ID` bigint(20) NOT NULL,
      `TAX_DETAIL_ID` bigint(20) NOT NULL,
      UNIQUE KEY `TAX_DETAIL_ID` (`TAX_DETAIL_ID`),
      KEY `FKDD3E8443E3BBB4D2` (`FULFILLMENT_GROUP_ITEM_ID`),
      KEY `FKDD3E844371448C19` (`TAX_DETAIL_ID`),
      CONSTRAINT `FKDD3E844371448C19` FOREIGN KEY (`TAX_DETAIL_ID`) REFERENCES `BLC_TAX_DETAIL` (`TAX_DETAIL_ID`),
      CONSTRAINT `FKDD3E8443E3BBB4D2` FOREIGN KEY (`FULFILLMENT_GROUP_ITEM_ID`) REFERENCES `BLC_FULFILLMENT_GROUP_ITEM` (`FULFILLMENT_GROUP_ITEM_ID`)
    ) ENGINE=InnoDB DEFAULT CHARSET=latin1;
    /*!40101 SET character_set_client = @saved_cs_client */;

    --
    -- Dumping data for table `BLC_FG_ITEM_TAX_XREF`
    --

    LOCK TABLES `BLC_FG_ITEM_TAX_XREF` WRITE;
    /*!40000 ALTER TABLE `BLC_FG_ITEM_TAX_XREF` DISABLE KEYS */;
    /*!40000 ALTER TABLE `BLC_FG_ITEM_TAX_XREF` ENABLE KEYS */;
    UNLOCK TABLES;
    
    DROP TABLE IF EXISTS `BLC_FULFILLMENT_OPTION`;
    /*!40101 SET @saved_cs_client     = @@character_set_client */;
    /*!40101 SET character_set_client = utf8 */;
    CREATE TABLE `BLC_FULFILLMENT_OPTION` (
      `FULFILLMENT_OPTION_ID` bigint(20) NOT NULL,
      `FULFILLMENT_TYPE` varchar(255) NOT NULL,
      `LONG_DESCRIPTION` longtext,
      `NAME` varchar(255) DEFAULT NULL,
      `USE_FLAT_RATES` bit(1) DEFAULT NULL,
      PRIMARY KEY (`FULFILLMENT_OPTION_ID`)
    ) ENGINE=InnoDB DEFAULT CHARSET=latin1;
    /*!40101 SET character_set_client = @saved_cs_client */;

    --
    -- Dumping data for table `BLC_FULFILLMENT_OPTION`
    --

    LOCK TABLES `BLC_FULFILLMENT_OPTION` WRITE;
    /*!40000 ALTER TABLE `BLC_FULFILLMENT_OPTION` DISABLE KEYS */;
    /*!40000 ALTER TABLE `BLC_FULFILLMENT_OPTION` ENABLE KEYS */;
    UNLOCK TABLES;

    --
    -- Table structure for table `BLC_FULFILLMENT_OPTION_FIXED`
    --

    DROP TABLE IF EXISTS `BLC_FULFILLMENT_OPTION_FIXED`;
    /*!40101 SET @saved_cs_client     = @@character_set_client */;
    /*!40101 SET character_set_client = utf8 */;
    CREATE TABLE `BLC_FULFILLMENT_OPTION_FIXED` (
      `PRICE` decimal(19,5) NOT NULL,
      `FULFILLMENT_OPTION_ID` bigint(20) NOT NULL,
      PRIMARY KEY (`FULFILLMENT_OPTION_ID`),
      KEY `FK4083603181F34C7F` (`FULFILLMENT_OPTION_ID`),
      CONSTRAINT `FK4083603181F34C7F` FOREIGN KEY (`FULFILLMENT_OPTION_ID`) REFERENCES `BLC_FULFILLMENT_OPTION` (`FULFILLMENT_OPTION_ID`)
    ) ENGINE=InnoDB DEFAULT CHARSET=latin1;
    /*!40101 SET character_set_client = @saved_cs_client */;

    --
    -- Dumping data for table `BLC_FULFILLMENT_OPTION_FIXED`
    --

    LOCK TABLES `BLC_FULFILLMENT_OPTION_FIXED` WRITE;
    /*!40000 ALTER TABLE `BLC_FULFILLMENT_OPTION_FIXED` DISABLE KEYS */;
    /*!40000 ALTER TABLE `BLC_FULFILLMENT_OPTION_FIXED` ENABLE KEYS */;
    UNLOCK TABLES;

    --
    -- Table structure for table `BLC_FULFILLMENT_OPT_BANDED_PRC`
    --

    DROP TABLE IF EXISTS `BLC_FULFILLMENT_OPT_BANDED_PRC`;
    /*!40101 SET @saved_cs_client     = @@character_set_client */;
    /*!40101 SET character_set_client = utf8 */;
    CREATE TABLE `BLC_FULFILLMENT_OPT_BANDED_PRC` (
      `FULFILLMENT_OPTION_ID` bigint(20) NOT NULL,
      PRIMARY KEY (`FULFILLMENT_OPTION_ID`),
      KEY `FKB1FD71E981F34C7F` (`FULFILLMENT_OPTION_ID`),
      CONSTRAINT `FKB1FD71E981F34C7F` FOREIGN KEY (`FULFILLMENT_OPTION_ID`) REFERENCES `BLC_FULFILLMENT_OPTION` (`FULFILLMENT_OPTION_ID`)
    ) ENGINE=InnoDB DEFAULT CHARSET=latin1;
    /*!40101 SET character_set_client = @saved_cs_client */;

    --
    -- Dumping data for table `BLC_FULFILLMENT_OPT_BANDED_PRC`
    --

    LOCK TABLES `BLC_FULFILLMENT_OPT_BANDED_PRC` WRITE;
    /*!40000 ALTER TABLE `BLC_FULFILLMENT_OPT_BANDED_PRC` DISABLE KEYS */;
    /*!40000 ALTER TABLE `BLC_FULFILLMENT_OPT_BANDED_PRC` ENABLE KEYS */;
    UNLOCK TABLES;

    --
    -- Table structure for table `BLC_FULFILLMENT_OPT_BANDED_WGT`
    --

    DROP TABLE IF EXISTS `BLC_FULFILLMENT_OPT_BANDED_WGT`;
    /*!40101 SET @saved_cs_client     = @@character_set_client */;
    /*!40101 SET character_set_client = utf8 */;
    CREATE TABLE `BLC_FULFILLMENT_OPT_BANDED_WGT` (
      `FULFILLMENT_OPTION_ID` bigint(20) NOT NULL,
      PRIMARY KEY (`FULFILLMENT_OPTION_ID`),
      KEY `FKB1FD8AEC81F34C7F` (`FULFILLMENT_OPTION_ID`),
      CONSTRAINT `FKB1FD8AEC81F34C7F` FOREIGN KEY (`FULFILLMENT_OPTION_ID`) REFERENCES `BLC_FULFILLMENT_OPTION` (`FULFILLMENT_OPTION_ID`)
    ) ENGINE=InnoDB DEFAULT CHARSET=latin1;
    /*!40101 SET character_set_client = @saved_cs_client */;

    --
    -- Dumping data for table `BLC_FULFILLMENT_OPT_BANDED_WGT`
    --

    LOCK TABLES `BLC_FULFILLMENT_OPT_BANDED_WGT` WRITE;
    /*!40000 ALTER TABLE `BLC_FULFILLMENT_OPT_BANDED_WGT` DISABLE KEYS */;
    /*!40000 ALTER TABLE `BLC_FULFILLMENT_OPT_BANDED_WGT` ENABLE KEYS */;
    UNLOCK TABLES;

    --
    -- Table structure for table `BLC_FULFILLMENT_PRICE_BAND`
    --

    DROP TABLE IF EXISTS `BLC_FULFILLMENT_PRICE_BAND`;
    /*!40101 SET @saved_cs_client     = @@character_set_client */;
    /*!40101 SET character_set_client = utf8 */;
    CREATE TABLE `BLC_FULFILLMENT_PRICE_BAND` (
      `FULFILLMENT_PRICE_BAND_ID` bigint(20) NOT NULL,
      `RESULT_AMOUNT` decimal(19,5) NOT NULL,
      `RESULT_AMOUNT_TYPE` varchar(255) NOT NULL,
      `RETAIL_PRICE_MINIMUM_AMOUNT` decimal(19,5) NOT NULL,
      `FULFILLMENT_OPTION_ID` bigint(20) DEFAULT NULL,
      PRIMARY KEY (`FULFILLMENT_PRICE_BAND_ID`),
      KEY `FK46C9EA726CDF59CA` (`FULFILLMENT_OPTION_ID`),
      CONSTRAINT `FK46C9EA726CDF59CA` FOREIGN KEY (`FULFILLMENT_OPTION_ID`) REFERENCES `BLC_FULFILLMENT_OPT_BANDED_PRC` (`FULFILLMENT_OPTION_ID`)
    ) ENGINE=InnoDB DEFAULT CHARSET=latin1;
    /*!40101 SET character_set_client = @saved_cs_client */;

    --
    -- Dumping data for table `BLC_FULFILLMENT_PRICE_BAND`
    --

    LOCK TABLES `BLC_FULFILLMENT_PRICE_BAND` WRITE;
    /*!40000 ALTER TABLE `BLC_FULFILLMENT_PRICE_BAND` DISABLE KEYS */;
    /*!40000 ALTER TABLE `BLC_FULFILLMENT_PRICE_BAND` ENABLE KEYS */;
    UNLOCK TABLES;

    --
    -- Table structure for table `BLC_FULFILLMENT_WEIGHT_BAND`
    --

    DROP TABLE IF EXISTS `BLC_FULFILLMENT_WEIGHT_BAND`;
    /*!40101 SET @saved_cs_client     = @@character_set_client */;
    /*!40101 SET character_set_client = utf8 */;
    CREATE TABLE `BLC_FULFILLMENT_WEIGHT_BAND` (
      `FULFILLMENT_WEIGHT_BAND_ID` bigint(20) NOT NULL,
      `RESULT_AMOUNT` decimal(19,5) NOT NULL,
      `RESULT_AMOUNT_TYPE` varchar(255) NOT NULL,
      `MINIMUM_WEIGHT` decimal(19,5) DEFAULT NULL,
      `FULFILLMENT_OPTION_ID` bigint(20) DEFAULT NULL,
      PRIMARY KEY (`FULFILLMENT_WEIGHT_BAND_ID`),
      KEY `FK6A048D95A0B429C3` (`FULFILLMENT_OPTION_ID`),
      CONSTRAINT `FK6A048D95A0B429C3` FOREIGN KEY (`FULFILLMENT_OPTION_ID`) REFERENCES `BLC_FULFILLMENT_OPT_BANDED_WGT` (`FULFILLMENT_OPTION_ID`)
    ) ENGINE=InnoDB DEFAULT CHARSET=latin1;
    /*!40101 SET character_set_client = @saved_cs_client */;

    --
    -- Dumping data for table `BLC_FULFILLMENT_WEIGHT_BAND`
    --

    LOCK TABLES `BLC_FULFILLMENT_WEIGHT_BAND` WRITE;
    /*!40000 ALTER TABLE `BLC_FULFILLMENT_WEIGHT_BAND` DISABLE KEYS */;
    /*!40000 ALTER TABLE `BLC_FULFILLMENT_WEIGHT_BAND` ENABLE KEYS */;
    UNLOCK TABLES;
    
    DROP TABLE IF EXISTS `BLC_ORDER_MULTISHIP_OPTION`;
    /*!40101 SET @saved_cs_client     = @@character_set_client */;
    /*!40101 SET character_set_client = utf8 */;
    CREATE TABLE `BLC_ORDER_MULTISHIP_OPTION` (
      `ORDER_MULTISHIP_OPTION_ID` bigint(20) NOT NULL,
      `ADDRESS_ID` bigint(20) DEFAULT NULL,
      `FULFILLMENT_OPTION_ID` bigint(20) DEFAULT NULL,
      `ORDER_ID` bigint(20) DEFAULT NULL,
      `ORDER_ITEM_ID` bigint(20) DEFAULT NULL,
      PRIMARY KEY (`ORDER_MULTISHIP_OPTION_ID`),
      KEY `MULTISHIP_OPTION_ORDER_INDEX` (`ORDER_ID`),
      KEY `FKB3D3F7D69AF166DF` (`ORDER_ITEM_ID`),
      KEY `FKB3D3F7D6C13085DD` (`ADDRESS_ID`),
      KEY `FKB3D3F7D689FE8A02` (`ORDER_ID`),
      KEY `FKB3D3F7D681F34C7F` (`FULFILLMENT_OPTION_ID`),
      CONSTRAINT `FKB3D3F7D681F34C7F` FOREIGN KEY (`FULFILLMENT_OPTION_ID`) REFERENCES `BLC_FULFILLMENT_OPTION` (`FULFILLMENT_OPTION_ID`),
      CONSTRAINT `FKB3D3F7D689FE8A02` FOREIGN KEY (`ORDER_ID`) REFERENCES `BLC_ORDER` (`ORDER_ID`),
      CONSTRAINT `FKB3D3F7D69AF166DF` FOREIGN KEY (`ORDER_ITEM_ID`) REFERENCES `BLC_ORDER_ITEM` (`ORDER_ITEM_ID`),
      CONSTRAINT `FKB3D3F7D6C13085DD` FOREIGN KEY (`ADDRESS_ID`) REFERENCES `BLC_ADDRESS` (`ADDRESS_ID`)
    ) ENGINE=InnoDB DEFAULT CHARSET=latin1;
    /*!40101 SET character_set_client = @saved_cs_client */;

    --
    -- Dumping data for table `BLC_ORDER_MULTISHIP_OPTION`
    --

    LOCK TABLES `BLC_ORDER_MULTISHIP_OPTION` WRITE;
    /*!40000 ALTER TABLE `BLC_ORDER_MULTISHIP_OPTION` DISABLE KEYS */;
    /*!40000 ALTER TABLE `BLC_ORDER_MULTISHIP_OPTION` ENABLE KEYS */;
    UNLOCK TABLES;
    
    DROP TABLE IF EXISTS `BLC_PAGE_ITEM_CRITERIA`;
    /*!40101 SET @saved_cs_client     = @@character_set_client */;
    /*!40101 SET character_set_client = utf8 */;
    CREATE TABLE `BLC_PAGE_ITEM_CRITERIA` (
      `PAGE_ITEM_CRITERIA_ID` bigint(20) NOT NULL,
      `ORDER_ITEM_MATCH_RULE` longtext,
      `QUANTITY` int(11) NOT NULL,
      PRIMARY KEY (`PAGE_ITEM_CRITERIA_ID`)
    ) ENGINE=InnoDB DEFAULT CHARSET=latin1;
    /*!40101 SET character_set_client = @saved_cs_client */;

    --
    -- Dumping data for table `BLC_PAGE_ITEM_CRITERIA`
    --

    LOCK TABLES `BLC_PAGE_ITEM_CRITERIA` WRITE;
    /*!40000 ALTER TABLE `BLC_PAGE_ITEM_CRITERIA` DISABLE KEYS */;
    /*!40000 ALTER TABLE `BLC_PAGE_ITEM_CRITERIA` ENABLE KEYS */;
    UNLOCK TABLES;

    --
    -- Table structure for table `BLC_PAGE_RULE`
    --

    DROP TABLE IF EXISTS `BLC_PAGE_RULE`;
    /*!40101 SET @saved_cs_client     = @@character_set_client */;
    /*!40101 SET character_set_client = utf8 */;
    CREATE TABLE `BLC_PAGE_RULE` (
      `PAGE_RULE_ID` bigint(20) NOT NULL,
      `MATCH_RULE` longtext,
      PRIMARY KEY (`PAGE_RULE_ID`)
    ) ENGINE=InnoDB DEFAULT CHARSET=latin1;
    /*!40101 SET character_set_client = @saved_cs_client */;

    --
    -- Dumping data for table `BLC_PAGE_RULE`
    --

    LOCK TABLES `BLC_PAGE_RULE` WRITE;
    /*!40000 ALTER TABLE `BLC_PAGE_RULE` DISABLE KEYS */;
    /*!40000 ALTER TABLE `BLC_PAGE_RULE` ENABLE KEYS */;
    UNLOCK TABLES;

    --
    -- Table structure for table `BLC_PAGE_RULE_MAP`
    --

    DROP TABLE IF EXISTS `BLC_PAGE_RULE_MAP`;
    /*!40101 SET @saved_cs_client     = @@character_set_client */;
    /*!40101 SET character_set_client = utf8 */;
    CREATE TABLE `BLC_PAGE_RULE_MAP` (
      `BLC_PAGE_PAGE_ID` bigint(20) NOT NULL,
      `PAGE_RULE_ID` bigint(20) NOT NULL,
      `MAP_KEY` varchar(255) NOT NULL,
      PRIMARY KEY (`BLC_PAGE_PAGE_ID`,`MAP_KEY`),
      KEY `FK1ABA0CA336D91846` (`PAGE_RULE_ID`),
      KEY `FK1ABA0CA3C38455DD` (`BLC_PAGE_PAGE_ID`),
      CONSTRAINT `FK1ABA0CA3C38455DD` FOREIGN KEY (`BLC_PAGE_PAGE_ID`) REFERENCES `BLC_PAGE` (`PAGE_ID`),
      CONSTRAINT `FK1ABA0CA336D91846` FOREIGN KEY (`PAGE_RULE_ID`) REFERENCES `BLC_PAGE_RULE` (`PAGE_RULE_ID`)
    ) ENGINE=InnoDB DEFAULT CHARSET=latin1;
    /*!40101 SET character_set_client = @saved_cs_client */;

    --
    -- Dumping data for table `BLC_PAGE_RULE_MAP`
    --

    LOCK TABLES `BLC_PAGE_RULE_MAP` WRITE;
    /*!40000 ALTER TABLE `BLC_PAGE_RULE_MAP` DISABLE KEYS */;
    /*!40000 ALTER TABLE `BLC_PAGE_RULE_MAP` ENABLE KEYS */;
    UNLOCK TABLES;
    
    DROP TABLE IF EXISTS `BLC_PRODUCT_BUNDLE`;
    /*!40101 SET @saved_cs_client     = @@character_set_client */;
    /*!40101 SET character_set_client = utf8 */;
    CREATE TABLE `BLC_PRODUCT_BUNDLE` (
      `AUTO_BUNDLE` bit(1) DEFAULT NULL,
      `BUNDLE_PROMOTABLE` bit(1) DEFAULT NULL,
      `ITEMS_PROMOTABLE` bit(1) DEFAULT NULL,
      `PRICING_MODEL` varchar(255) DEFAULT NULL,
      `BUNDLE_PRIORITY` int(11) DEFAULT NULL,
      `PRODUCT_ID` bigint(20) NOT NULL,
      PRIMARY KEY (`PRODUCT_ID`),
      KEY `FK8CC5B85F11A0B7` (`PRODUCT_ID`),
      CONSTRAINT `FK8CC5B85F11A0B7` FOREIGN KEY (`PRODUCT_ID`) REFERENCES `BLC_PRODUCT` (`PRODUCT_ID`)
    ) ENGINE=InnoDB DEFAULT CHARSET=latin1;
    /*!40101 SET character_set_client = @saved_cs_client */;

    --
    -- Dumping data for table `BLC_PRODUCT_BUNDLE`
    --

    LOCK TABLES `BLC_PRODUCT_BUNDLE` WRITE;
    /*!40000 ALTER TABLE `BLC_PRODUCT_BUNDLE` DISABLE KEYS */;
    /*!40000 ALTER TABLE `BLC_PRODUCT_BUNDLE` ENABLE KEYS */;
    UNLOCK TABLES;
    
    DROP TABLE IF EXISTS `BLC_PRODUCT_OPTION`;
    /*!40101 SET @saved_cs_client     = @@character_set_client */;
    /*!40101 SET character_set_client = utf8 */;
    CREATE TABLE `BLC_PRODUCT_OPTION` (
      `PRODUCT_OPTION_ID` bigint(20) NOT NULL,
      `ATTRIBUTE_NAME` varchar(255) DEFAULT NULL,
      `LABEL` varchar(255) DEFAULT NULL,
      `REQUIRED` bit(1) DEFAULT NULL,
      `OPTION_TYPE` varchar(255) DEFAULT NULL,
      PRIMARY KEY (`PRODUCT_OPTION_ID`)
    ) ENGINE=InnoDB DEFAULT CHARSET=latin1;
    /*!40101 SET character_set_client = @saved_cs_client */;

    --
    -- Dumping data for table `BLC_PRODUCT_OPTION`
    --

    LOCK TABLES `BLC_PRODUCT_OPTION` WRITE;
    /*!40000 ALTER TABLE `BLC_PRODUCT_OPTION` DISABLE KEYS */;
    /*!40000 ALTER TABLE `BLC_PRODUCT_OPTION` ENABLE KEYS */;
    UNLOCK TABLES;

    --
    -- Table structure for table `BLC_PRODUCT_OPTION_VALUE`
    --

    DROP TABLE IF EXISTS `BLC_PRODUCT_OPTION_VALUE`;
    /*!40101 SET @saved_cs_client     = @@character_set_client */;
    /*!40101 SET character_set_client = utf8 */;
    CREATE TABLE `BLC_PRODUCT_OPTION_VALUE` (
      `PRODUCT_OPTION_VALUE_ID` bigint(20) NOT NULL,
      `ATTRIBUTE_VALUE` varchar(255) DEFAULT NULL,
      `DISPLAY_ORDER` bigint(20) DEFAULT NULL,
      `PRICE_ADJUSTMENT` decimal(19,5) DEFAULT NULL,
      `PRODUCT_OPTION_ID` bigint(20) DEFAULT NULL,
      PRIMARY KEY (`PRODUCT_OPTION_VALUE_ID`),
      KEY `FK6DEEEDBD92EA8136` (`PRODUCT_OPTION_ID`),
      CONSTRAINT `FK6DEEEDBD92EA8136` FOREIGN KEY (`PRODUCT_OPTION_ID`) REFERENCES `BLC_PRODUCT_OPTION` (`PRODUCT_OPTION_ID`)
    ) ENGINE=InnoDB DEFAULT CHARSET=latin1;
    /*!40101 SET character_set_client = @saved_cs_client */;

    --
    -- Dumping data for table `BLC_PRODUCT_OPTION_VALUE`
    --

    LOCK TABLES `BLC_PRODUCT_OPTION_VALUE` WRITE;
    /*!40000 ALTER TABLE `BLC_PRODUCT_OPTION_VALUE` DISABLE KEYS */;
    /*!40000 ALTER TABLE `BLC_PRODUCT_OPTION_VALUE` ENABLE KEYS */;
    UNLOCK TABLES;

    --
    -- Table structure for table `BLC_PRODUCT_OPTION_XREF`
    --

    DROP TABLE IF EXISTS `BLC_PRODUCT_OPTION_XREF`;
    /*!40101 SET @saved_cs_client     = @@character_set_client */;
    /*!40101 SET character_set_client = utf8 */;
    CREATE TABLE `BLC_PRODUCT_OPTION_XREF` (
      `PRODUCT_OPTION_ID` bigint(20) NOT NULL,
      `PRODUCT_ID` bigint(20) NOT NULL,
      KEY `FKDA42AB2F92EA8136` (`PRODUCT_OPTION_ID`),
      KEY `FKDA42AB2F5F11A0B7` (`PRODUCT_ID`),
      CONSTRAINT `FKDA42AB2F5F11A0B7` FOREIGN KEY (`PRODUCT_ID`) REFERENCES `BLC_PRODUCT` (`PRODUCT_ID`),
      CONSTRAINT `FKDA42AB2F92EA8136` FOREIGN KEY (`PRODUCT_OPTION_ID`) REFERENCES `BLC_PRODUCT_OPTION` (`PRODUCT_OPTION_ID`)
    ) ENGINE=InnoDB DEFAULT CHARSET=latin1;
    /*!40101 SET character_set_client = @saved_cs_client */;

    --
    -- Dumping data for table `BLC_PRODUCT_OPTION_XREF`
    --

    LOCK TABLES `BLC_PRODUCT_OPTION_XREF` WRITE;
    /*!40000 ALTER TABLE `BLC_PRODUCT_OPTION_XREF` DISABLE KEYS */;
    /*!40000 ALTER TABLE `BLC_PRODUCT_OPTION_XREF` ENABLE KEYS */;
    UNLOCK TABLES;
    
    DROP TABLE IF EXISTS `BLC_QUAL_CRIT_PAGE_XREF`;
    /*!40101 SET @saved_cs_client     = @@character_set_client */;
    /*!40101 SET character_set_client = utf8 */;
    CREATE TABLE `BLC_QUAL_CRIT_PAGE_XREF` (
      `PAGE_ID` bigint(20) NOT NULL DEFAULT '0',
      `PAGE_ITEM_CRITERIA_ID` bigint(20) NOT NULL,
      PRIMARY KEY (`PAGE_ID`,`PAGE_ITEM_CRITERIA_ID`),
      UNIQUE KEY `PAGE_ITEM_CRITERIA_ID` (`PAGE_ITEM_CRITERIA_ID`),
      KEY `FK874BE590378418CD` (`PAGE_ITEM_CRITERIA_ID`),
      KEY `FK874BE590883C2667` (`PAGE_ID`),
      CONSTRAINT `FK874BE590883C2667` FOREIGN KEY (`PAGE_ID`) REFERENCES `BLC_PAGE` (`PAGE_ID`),
      CONSTRAINT `FK874BE590378418CD` FOREIGN KEY (`PAGE_ITEM_CRITERIA_ID`) REFERENCES `BLC_PAGE_ITEM_CRITERIA` (`PAGE_ITEM_CRITERIA_ID`)
    ) ENGINE=InnoDB DEFAULT CHARSET=latin1;
    /*!40101 SET character_set_client = @saved_cs_client */;

    --
    -- Dumping data for table `BLC_QUAL_CRIT_PAGE_XREF`
    --

    LOCK TABLES `BLC_QUAL_CRIT_PAGE_XREF` WRITE;
    /*!40000 ALTER TABLE `BLC_QUAL_CRIT_PAGE_XREF` DISABLE KEYS */;
    /*!40000 ALTER TABLE `BLC_QUAL_CRIT_PAGE_XREF` ENABLE KEYS */;
    UNLOCK TABLES;
    
    DROP TABLE IF EXISTS `BLC_SEARCH_FACET`;
    /*!40101 SET @saved_cs_client     = @@character_set_client */;
    /*!40101 SET character_set_client = utf8 */;
    CREATE TABLE `BLC_SEARCH_FACET` (
      `SEARCH_FACET_ID` bigint(20) NOT NULL,
      `FIELD_NAME` varchar(255) NOT NULL,
      `LABEL` varchar(255) DEFAULT NULL,
      `QUERY_STRING_KEY` varchar(255) NOT NULL,
      `SEARCH_DISPLAY_PRIORITY` int(11) DEFAULT NULL,
      `SHOW_ON_SEARCH` bit(1) DEFAULT NULL,
      PRIMARY KEY (`SEARCH_FACET_ID`)
    ) ENGINE=InnoDB DEFAULT CHARSET=latin1;
    /*!40101 SET character_set_client = @saved_cs_client */;

    --
    -- Dumping data for table `BLC_SEARCH_FACET`
    --

    LOCK TABLES `BLC_SEARCH_FACET` WRITE;
    /*!40000 ALTER TABLE `BLC_SEARCH_FACET` DISABLE KEYS */;
    /*!40000 ALTER TABLE `BLC_SEARCH_FACET` ENABLE KEYS */;
    UNLOCK TABLES;

    --
    -- Table structure for table `BLC_SEARCH_FACET_RANGE`
    --

    DROP TABLE IF EXISTS `BLC_SEARCH_FACET_RANGE`;
    /*!40101 SET @saved_cs_client     = @@character_set_client */;
    /*!40101 SET character_set_client = utf8 */;
    CREATE TABLE `BLC_SEARCH_FACET_RANGE` (
      `SEARCH_FACET_RANGE_ID` bigint(20) NOT NULL,
      `MAX_VALUE` decimal(19,5) DEFAULT NULL,
      `MIN_VALUE` decimal(19,5) NOT NULL,
      `SEARCH_FACET_ID` bigint(20) NOT NULL,
      PRIMARY KEY (`SEARCH_FACET_RANGE_ID`),
      KEY `SEARCH_FACET_INDEX` (`SEARCH_FACET_ID`),
      KEY `FK7EC3B124B96B1C93` (`SEARCH_FACET_ID`),
      CONSTRAINT `FK7EC3B124B96B1C93` FOREIGN KEY (`SEARCH_FACET_ID`) REFERENCES `BLC_SEARCH_FACET` (`SEARCH_FACET_ID`)
    ) ENGINE=InnoDB DEFAULT CHARSET=latin1;
    /*!40101 SET character_set_client = @saved_cs_client */;

    --
    -- Dumping data for table `BLC_SEARCH_FACET_RANGE`
    --

    LOCK TABLES `BLC_SEARCH_FACET_RANGE` WRITE;
    /*!40000 ALTER TABLE `BLC_SEARCH_FACET_RANGE` DISABLE KEYS */;
    /*!40000 ALTER TABLE `BLC_SEARCH_FACET_RANGE` ENABLE KEYS */;
    UNLOCK TABLES;
    
    DROP TABLE IF EXISTS `BLC_SKU_BUNDLE_ITEM`;
    /*!40101 SET @saved_cs_client     = @@character_set_client */;
    /*!40101 SET character_set_client = utf8 */;
    CREATE TABLE `BLC_SKU_BUNDLE_ITEM` (
      `SKU_BUNDLE_ITEM_ID` bigint(20) NOT NULL,
      `ITEM_SALE_PRICE` decimal(19,5) DEFAULT NULL,
      `QUANTITY` int(11) NOT NULL,
      `PRODUCT_BUNDLE_ID` bigint(20) NOT NULL,
      `SKU_ID` bigint(20) NOT NULL,
      PRIMARY KEY (`SKU_BUNDLE_ITEM_ID`),
      UNIQUE KEY `SKU_ID` (`SKU_ID`),
      KEY `FKD55968B78C9977` (`SKU_ID`),
      KEY `FKD55968CCF29B96` (`PRODUCT_BUNDLE_ID`),
      CONSTRAINT `FKD55968CCF29B96` FOREIGN KEY (`PRODUCT_BUNDLE_ID`) REFERENCES `BLC_PRODUCT_BUNDLE` (`PRODUCT_ID`),
      CONSTRAINT `FKD55968B78C9977` FOREIGN KEY (`SKU_ID`) REFERENCES `BLC_SKU` (`SKU_ID`)
    ) ENGINE=InnoDB DEFAULT CHARSET=latin1;
    /*!40101 SET character_set_client = @saved_cs_client */;

    --
    -- Dumping data for table `BLC_SKU_BUNDLE_ITEM`
    --

    LOCK TABLES `BLC_SKU_BUNDLE_ITEM` WRITE;
    /*!40000 ALTER TABLE `BLC_SKU_BUNDLE_ITEM` DISABLE KEYS */;
    /*!40000 ALTER TABLE `BLC_SKU_BUNDLE_ITEM` ENABLE KEYS */;
    UNLOCK TABLES;

    --
    -- Table structure for table `BLC_SKU_FEE`
    --

    DROP TABLE IF EXISTS `BLC_SKU_FEE`;
    /*!40101 SET @saved_cs_client     = @@character_set_client */;
    /*!40101 SET character_set_client = utf8 */;
    CREATE TABLE `BLC_SKU_FEE` (
      `SKU_FEE_ID` bigint(20) NOT NULL,
      `AMOUNT` decimal(19,5) NOT NULL,
      `DESCRIPTION` varchar(255) DEFAULT NULL,
      `EXPRESSION` longtext,
      `FEE_TYPE` varchar(255) DEFAULT NULL,
      `NAME` varchar(255) DEFAULT NULL,
      `TAXABLE` bit(1) DEFAULT NULL,
      PRIMARY KEY (`SKU_FEE_ID`)
    ) ENGINE=InnoDB DEFAULT CHARSET=latin1;
    /*!40101 SET character_set_client = @saved_cs_client */;

    --
    -- Dumping data for table `BLC_SKU_FEE`
    --

    LOCK TABLES `BLC_SKU_FEE` WRITE;
    /*!40000 ALTER TABLE `BLC_SKU_FEE` DISABLE KEYS */;
    /*!40000 ALTER TABLE `BLC_SKU_FEE` ENABLE KEYS */;
    UNLOCK TABLES;

    --
    -- Table structure for table `BLC_SKU_FEE_XREF`
    --

    DROP TABLE IF EXISTS `BLC_SKU_FEE_XREF`;
    /*!40101 SET @saved_cs_client     = @@character_set_client */;
    /*!40101 SET character_set_client = utf8 */;
    CREATE TABLE `BLC_SKU_FEE_XREF` (
      `SKU_FEE_ID` bigint(20) NOT NULL,
      `SKU_ID` bigint(20) NOT NULL,
      KEY `FKD88D409CB78C9977` (`SKU_ID`),
      KEY `FKD88D409CCF4C9A82` (`SKU_FEE_ID`),
      CONSTRAINT `FKD88D409CCF4C9A82` FOREIGN KEY (`SKU_FEE_ID`) REFERENCES `BLC_SKU_FEE` (`SKU_FEE_ID`),
      CONSTRAINT `FKD88D409CB78C9977` FOREIGN KEY (`SKU_ID`) REFERENCES `BLC_SKU` (`SKU_ID`)
    ) ENGINE=InnoDB DEFAULT CHARSET=latin1;
    /*!40101 SET character_set_client = @saved_cs_client */;

    --
    -- Dumping data for table `BLC_SKU_FEE_XREF`
    --

    LOCK TABLES `BLC_SKU_FEE_XREF` WRITE;
    /*!40000 ALTER TABLE `BLC_SKU_FEE_XREF` DISABLE KEYS */;
    /*!40000 ALTER TABLE `BLC_SKU_FEE_XREF` ENABLE KEYS */;
    UNLOCK TABLES;

    --
    -- Table structure for table `BLC_SKU_FULFILLMENT_EXCLUDED`
    --

    DROP TABLE IF EXISTS `BLC_SKU_FULFILLMENT_EXCLUDED`;
    /*!40101 SET @saved_cs_client     = @@character_set_client */;
    /*!40101 SET character_set_client = utf8 */;
    CREATE TABLE `BLC_SKU_FULFILLMENT_EXCLUDED` (
      `SKU_ID` bigint(20) NOT NULL,
      `FULFILLMENT_OPTION_ID` bigint(20) NOT NULL,
      KEY `FK84162D73B78C9977` (`SKU_ID`),
      KEY `FK84162D7381F34C7F` (`FULFILLMENT_OPTION_ID`),
      CONSTRAINT `FK84162D7381F34C7F` FOREIGN KEY (`FULFILLMENT_OPTION_ID`) REFERENCES `BLC_FULFILLMENT_OPTION` (`FULFILLMENT_OPTION_ID`),
      CONSTRAINT `FK84162D73B78C9977` FOREIGN KEY (`SKU_ID`) REFERENCES `BLC_SKU` (`SKU_ID`)
    ) ENGINE=InnoDB DEFAULT CHARSET=latin1;
    /*!40101 SET character_set_client = @saved_cs_client */;

    --
    -- Dumping data for table `BLC_SKU_FULFILLMENT_EXCLUDED`
    --

    LOCK TABLES `BLC_SKU_FULFILLMENT_EXCLUDED` WRITE;
    /*!40000 ALTER TABLE `BLC_SKU_FULFILLMENT_EXCLUDED` DISABLE KEYS */;
    /*!40000 ALTER TABLE `BLC_SKU_FULFILLMENT_EXCLUDED` ENABLE KEYS */;
    UNLOCK TABLES;

    --
    -- Table structure for table `BLC_SKU_FULFILLMENT_FLAT_RATES`
    --

    DROP TABLE IF EXISTS `BLC_SKU_FULFILLMENT_FLAT_RATES`;
    /*!40101 SET @saved_cs_client     = @@character_set_client */;
    /*!40101 SET character_set_client = utf8 */;
    CREATE TABLE `BLC_SKU_FULFILLMENT_FLAT_RATES` (
      `SKU_ID` bigint(20) NOT NULL,
      `RATE` decimal(19,5) DEFAULT NULL,
      `FULFILLMENT_OPTION_ID` bigint(20) NOT NULL,
      PRIMARY KEY (`SKU_ID`,`FULFILLMENT_OPTION_ID`),
      KEY `FKC1988C96B78C9977` (`SKU_ID`),
      KEY `FKC1988C9681F34C7F` (`FULFILLMENT_OPTION_ID`),
      CONSTRAINT `FKC1988C9681F34C7F` FOREIGN KEY (`FULFILLMENT_OPTION_ID`) REFERENCES `BLC_FULFILLMENT_OPTION` (`FULFILLMENT_OPTION_ID`),
      CONSTRAINT `FKC1988C96B78C9977` FOREIGN KEY (`SKU_ID`) REFERENCES `BLC_SKU` (`SKU_ID`)
    ) ENGINE=InnoDB DEFAULT CHARSET=latin1;
    /*!40101 SET character_set_client = @saved_cs_client */;

    --
    -- Dumping data for table `BLC_SKU_FULFILLMENT_FLAT_RATES`
    --

    LOCK TABLES `BLC_SKU_FULFILLMENT_FLAT_RATES` WRITE;
    /*!40000 ALTER TABLE `BLC_SKU_FULFILLMENT_FLAT_RATES` DISABLE KEYS */;
    /*!40000 ALTER TABLE `BLC_SKU_FULFILLMENT_FLAT_RATES` ENABLE KEYS */;
    UNLOCK TABLES;
    
    DROP TABLE IF EXISTS `BLC_SKU_OPTION_VALUE_XREF`;
    /*!40101 SET @saved_cs_client     = @@character_set_client */;
    /*!40101 SET character_set_client = utf8 */;
    CREATE TABLE `BLC_SKU_OPTION_VALUE_XREF` (
      `SKU_ID` bigint(20) NOT NULL,
      `PRODUCT_OPTION_VALUE_ID` bigint(20) NOT NULL,
      KEY `FK7B61DC0BB78C9977` (`SKU_ID`),
      KEY `FK7B61DC0BB0C16A73` (`PRODUCT_OPTION_VALUE_ID`),
      CONSTRAINT `FK7B61DC0BB0C16A73` FOREIGN KEY (`PRODUCT_OPTION_VALUE_ID`) REFERENCES `BLC_PRODUCT_OPTION_VALUE` (`PRODUCT_OPTION_VALUE_ID`),
      CONSTRAINT `FK7B61DC0BB78C9977` FOREIGN KEY (`SKU_ID`) REFERENCES `BLC_SKU` (`SKU_ID`)
    ) ENGINE=InnoDB DEFAULT CHARSET=latin1;
    /*!40101 SET character_set_client = @saved_cs_client */;

    --
    -- Dumping data for table `BLC_SKU_OPTION_VALUE_XREF`
    --

    LOCK TABLES `BLC_SKU_OPTION_VALUE_XREF` WRITE;
    /*!40000 ALTER TABLE `BLC_SKU_OPTION_VALUE_XREF` DISABLE KEYS */;
    /*!40000 ALTER TABLE `BLC_SKU_OPTION_VALUE_XREF` ENABLE KEYS */;
    UNLOCK TABLES;
    
    DROP TABLE IF EXISTS `BLC_SYSTEM_PROPERTY`;
    /*!40101 SET @saved_cs_client     = @@character_set_client */;
    /*!40101 SET character_set_client = utf8 */;
    CREATE TABLE `BLC_SYSTEM_PROPERTY` (
      `BLC_SYSTEM_PROPERTY_ID` bigint(20) NOT NULL,
      `PROPERTY_NAME` varchar(255) NOT NULL,
      `PROPERTY_VALUE` varchar(255) NOT NULL,
      PRIMARY KEY (`BLC_SYSTEM_PROPERTY_ID`),
      UNIQUE KEY `PROPERTY_NAME` (`PROPERTY_NAME`)
    ) ENGINE=InnoDB DEFAULT CHARSET=latin1;
    /*!40101 SET character_set_client = @saved_cs_client */;

    --
    -- Dumping data for table `BLC_SYSTEM_PROPERTY`
    --

    LOCK TABLES `BLC_SYSTEM_PROPERTY` WRITE;
    /*!40000 ALTER TABLE `BLC_SYSTEM_PROPERTY` DISABLE KEYS */;
    /*!40000 ALTER TABLE `BLC_SYSTEM_PROPERTY` ENABLE KEYS */;
    UNLOCK TABLES;
    
    DROP TABLE IF EXISTS `BLC_TAX_DETAIL`;
    /*!40101 SET @saved_cs_client     = @@character_set_client */;
    /*!40101 SET character_set_client = utf8 */;
    CREATE TABLE `BLC_TAX_DETAIL` (
      `TAX_DETAIL_ID` bigint(20) NOT NULL,
      `AMOUNT` tinyblob,
      `RATE` decimal(19,5) DEFAULT NULL,
      `TYPE` tinyblob,
      PRIMARY KEY (`TAX_DETAIL_ID`)
    ) ENGINE=InnoDB DEFAULT CHARSET=latin1;
    /*!40101 SET character_set_client = @saved_cs_client */;

    --
    -- Dumping data for table `BLC_TAX_DETAIL`
    --

    LOCK TABLES `BLC_TAX_DETAIL` WRITE;
    /*!40000 ALTER TABLE `BLC_TAX_DETAIL` DISABLE KEYS */;
    /*!40000 ALTER TABLE `BLC_TAX_DETAIL` ENABLE KEYS */;
    UNLOCK TABLES;

    --
    -- Table structure for table `BLC_URL_HANDLER`
    --

    DROP TABLE IF EXISTS `BLC_URL_HANDLER`;
    /*!40101 SET @saved_cs_client     = @@character_set_client */;
    /*!40101 SET character_set_client = utf8 */;
    CREATE TABLE `BLC_URL_HANDLER` (
      `URL_HANDLER_ID` bigint(20) NOT NULL,
      `INCOMING_URL` varchar(255) NOT NULL,
      `NEW_URL` varchar(255) NOT NULL,
      `URL_REDIRECT_TYPE` varchar(255) DEFAULT NULL,
      PRIMARY KEY (`URL_HANDLER_ID`)
    ) ENGINE=InnoDB DEFAULT CHARSET=latin1;
    /*!40101 SET character_set_client = @saved_cs_client */;

    --
    -- Dumping data for table `BLC_URL_HANDLER`
    --

    LOCK TABLES `BLC_URL_HANDLER` WRITE;
    /*!40000 ALTER TABLE `BLC_URL_HANDLER` DISABLE KEYS */;
    /*!40000 ALTER TABLE `BLC_URL_HANDLER` ENABLE KEYS */;

